version: '3'

services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8878:80
    depends_on:
      - app
    container_name: blog_api_nginx
    
  app:
   build:
    context: .
    dockerfile: _docker/app/Dockerfile
   volumes:
     - ./:/var/www/
   user: 1000:1000
   depends_on: 
     - db
   container_name: blog_api_app

  db:
   image: mysql:8.0-oracle
   restart: always
   volumes:
     - ./tmp/db:/var/lib/mysql
   environment: 
    MYSQL_DATABASE: blog_api 
    MYSQL_ROOT_PASSWORD: root
   ports:
     - 8104:3306
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci 
   container_name: project_db

  db_test:
   image: mysql:8.0-oracle
   restart: always
   volumes:
     - ./tmp/db:/var/lib/mysql
   environment: 
    MYSQL_DATABASE: blog_api 
    MYSQL_ROOT_PASSWORD: root
   ports:
     - 8105:3306
   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci 
   container_name: project_db_test